# Generated by Django 2.2.10 on 2020-06-17 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servico', models.CharField(max_length=255)),
                ('sessao', models.CharField(max_length=3)),
                ('data', models.DateField()),
                ('hora_inicio', models.CharField(choices=[('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30')], max_length=5)),
                ('hora_fim', models.CharField(choices=[('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30')], max_length=5)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('sexo', models.CharField(blank=True, choices=[['Feminino', 'Feminino'], ['Masculino', 'Masculino']], max_length=9, null=True)),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='profile', verbose_name='Foto de perfil')),
                ('tel_fixo', models.CharField(blank=True, max_length=15, verbose_name='Telefone Residencial')),
                ('tel_cel', models.CharField(blank=True, max_length=15, verbose_name='Telefone Celular')),
                ('tel_emergency', models.CharField(blank=True, max_length=15, verbose_name='Telefone Emergência')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cep', models.CharField(default='', max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(default='', max_length=100, verbose_name='Endereço')),
                ('numero', models.CharField(default=0, max_length=5, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=30, verbose_name='Complemento')),
                ('bairro', models.CharField(default='', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(default='', max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(default='', max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('status', models.CharField(choices=[('0', 'A Pagar'), ('1', 'Pago')], max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data do pedido')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor Total')),
                ('desconto', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Desconto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pedido', to='web.ClienteModel', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=50, unique=True, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor')),
                ('descricao', models.TextField(default='', verbose_name='Descrição')),
                ('images', models.FileField(blank=True, upload_to='servicos/imagens/', verbose_name='Imagens')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='RegistroSessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, default='')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data do Registro')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Agenda')),
            ],
            options={
                'verbose_name': 'Registro de atendimento',
                'verbose_name_plural': 'Registros de atendimentos',
            },
        ),
        migrations.CreateModel(
            name='PedidoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=255, verbose_name='Serviço')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Subtotal')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_det', to='web.Pedido')),
            ],
            options={
                'verbose_name': 'Pedido Details',
                'verbose_name_plural': 'Pedidos Details',
            },
        ),
        migrations.CreateModel(
            name='FichaAnamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamento_anterior', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Tratamento Anterior')),
                ('lentes_contato', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Lentes de contato')),
                ('cosmeticos', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Cosméticos')),
                ('exposicao_sol', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Exposição ao Sol')),
                ('filtro_solar', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Filtro Solar')),
                ('tabagismo', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Tabagismo')),
                ('bebida_alcoolica', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Bebida Alcoólica')),
                ('intestino', models.CharField(choices=[('1', 'Bom'), ('2', 'Regular'), ('3', 'Péssimo')], max_length=1)),
                ('sono', models.CharField(choices=[('1', 'Bom'), ('2', 'Regular'), ('3', 'Péssimo')], max_length=1)),
                ('alimentacao', models.CharField(choices=[('1', 'Bom'), ('2', 'Regular'), ('3', 'Péssimo')], max_length=1)),
                ('agua', models.CharField(choices=[('1', 'Bom'), ('2', 'Regular'), ('3', 'Péssimo')], max_length=1)),
                ('atv_fisica', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Atividade Física')),
                ('anticoncepcional', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Anticoncepcional')),
                ('gestante', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Gestante')),
                ('tratamento_medico', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Tratamento Médico')),
                ('alergias', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Antecedentes Alérgicos')),
                ('marcapasso', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Portador de Marcapasso')),
                ('cardiaco', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Alterações Cardíacas')),
                ('h_tensao', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Hipo/hipertensão arterial')),
                ('d_circulatorio', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Distúrbio Circulatório')),
                ('d_renal', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Distúrbio Renal')),
                ('d_hormonal', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Distúrbio Hormonal')),
                ('d_gastro', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Distúrbio gastro-intestinal')),
                ('epilepsia', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Epilepsia- convulsões')),
                ('alteracoes_psic', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Alterações psicológicas/ psiquiátricas')),
                ('estresse', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Estresse')),
                ('diabetes', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Diabetes')),
                ('doenca', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], max_length=1, verbose_name='Algum tipo de doença')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_cliente', to='web.ClienteModel', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Ficha Anamnese',
                'verbose_name_plural': 'Fichas Anamnese',
            },
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('foto', models.ImageField(blank=True, default='default.png', upload_to='users', verbose_name='Foto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_agenda', to='web.ClienteModel', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_agenda', to='web.Pedido', verbose_name='pedido'),
        ),
    ]
