# Generated by Django 2.2.10 on 2020-04-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='hora_inicio',
            new_name='hora',
        ),
    ]
