# Generated by Django 2.2.10 on 2020-04-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetail',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Desconto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidodetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Subtotal'),
        ),
    ]
