# Generated by Django 2.2.10 on 2020-04-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200416_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetail',
            name='desconto',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Desconto'),
        ),
    ]
