# Generated by Django 2.2.10 on 2020-04-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200423_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='hora',
            new_name='hora_inicio',
        ),
    ]
