# Generated by Django 2.2.10 on 2020-05-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200524_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='sessao',
            field=models.CharField(max_length=3, verbose_name='Sessão'),
        ),
    ]
