# Generated by Django 2.2.10 on 2020-05-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200524_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='servico',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='sessao',
            field=models.CharField(max_length=3),
        ),
    ]
