# Generated by Django 2.2.10 on 2020-05-25 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200524_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_agenda', to='web.Pedido', verbose_name='pedido'),
        ),
    ]
