# Generated by Django 2.2.10 on 2020-04-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200417_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=7, verbose_name='Valor Total'),
            preserve_default=False,
        ),
    ]
