# Generated by Django 2.2.10 on 2020-06-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(default='')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Agenda')),
            ],
        ),
    ]
