# Generated by Django 2.2.10 on 2020-04-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_pedido_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodetail',
            name='desconto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Desconto'),
        ),
    ]
