# Generated by Django 2.2.10 on 2020-06-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_registrosessao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosessao',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
