# Generated by Django 2.2.10 on 2020-04-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200417_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAnamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamento_anterior', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_cliente', to='web.ClienteModel', verbose_name='cliente')),
            ],
        ),
    ]
