# Generated by Django 2.2.10 on 2020-04-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_fichaanamnese'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaanamnese',
            name='alimentação',
            field=models.CharField(choices=[('1', 'Bom'), ('2', 'Regular'), ('3', 'Péssimo')], default=0, max_length=1, verbose_name='Alimentação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='anticoncepcional',
            field=models.BooleanField(default=0, verbose_name='Anticoncepcional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='atv_fisica',
            field=models.BooleanField(default=0, verbose_name='Atividade Física'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='bebida_alcoolica',
            field=models.BooleanField(default=0, verbose_name='Bebida Alcoólica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='cosmeticos',
            field=models.BooleanField(default=0, verbose_name='Cosméticos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='exposicao_sol',
            field=models.BooleanField(default=0, verbose_name='Exposição ao Sol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='filtro_solar',
            field=models.BooleanField(default=0, verbose_name='Filtro Solar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='gestante',
            field=models.BooleanField(default=0, verbose_name='Gestante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='intestino',
            field=models.CharField(choices=[('1', 'Bom'), ('2', 'Regular'), ('3', 'Péssimo')], default=0, max_length=1, verbose_name='Funcionamento Intestino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='lentes_contato',
            field=models.BooleanField(default=1, verbose_name='Lentes de contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='sono',
            field=models.CharField(choices=[('1', 'Bom'), ('2', 'Regular'), ('3', 'Péssimo')], default=1, max_length=1, verbose_name='Qualidade do sono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='tabagismo',
            field=models.BooleanField(default=1, verbose_name='Tabagismo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='tratamento_anterior',
            field=models.BooleanField(verbose_name='Tratamento Anterior'),
        ),
    ]
