# Generated by Django 2.2.10 on 2020-04-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200425_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data',
            field=models.DateField(),
        ),
    ]
