# Generated by Django 2.2 on 2020-03-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_clientemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='clientes/profiles'),
        ),
    ]
