# Generated by Django 2.2.10 on 2020-06-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_despesas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesas',
            name='Status',
        ),
        migrations.AddField(
            model_name='despesas',
            name='status',
            field=models.CharField(choices=[('0', 'A Pagar'), ('1', 'Pago')], default=1, max_length=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
