# Generated by Django 2.2.10 on 2020-04-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200417_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichaanamnese',
            old_name='alimentação',
            new_name='alimentacao',
        ),
    ]
