# Generated by Django 2.2.10 on 2020-06-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20200609_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaanamnese',
            name='agua',
            field=models.CharField(choices=[('1', 'Bom'), ('2', 'Regular'), ('3', 'Péssimo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
