# Generated by Django 2.2.10 on 2020-04-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200427_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
    ]
