# Generated by Django 2.2.10 on 2020-06-16 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0012_fichaanamnese_agua'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Custom',
        ),
    ]
