# Generated by Django 2.2.10 on 2020-04-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200417_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaanamnese',
            name='alergias',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Antecedentes Alérgicos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='alteracoes_psic',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Alterações psicológicas/ psiquiátricas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='cardiaco',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Alterações Cardíacas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='d_circulatorio',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Distúrbio Circulatório'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='d_gastro',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Distúrbio gastro-intestinal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='d_hormonal',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Distúrbio Hormonal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='diabetes',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Diabetes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='doenca',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Algum tipo de doença'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='epilepsia',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Epilepsia- convulsões'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='estresse',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Estresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='h_tensao',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Hipo/hipertensão arterial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='marcapasso',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Portador de Marcapasso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaanamnese',
            name='tratamento_medico',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Tratamento Médico'),
            preserve_default=False,
        ),
    ]
