# Generated by Django 2.2.10 on 2020-04-27 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200427_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendar_servico', to='web.PedidoDetail'),
            preserve_default=False,
        ),
    ]
