# Generated by Django 2.2.10 on 2020-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200616_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='users', verbose_name='Foto'),
        ),
    ]
