# Generated by Django 2.2.10 on 2020-04-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200417_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaanamnese',
            name='d_renal',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, verbose_name='Distúrbio Renal'),
            preserve_default=False,
        ),
    ]
