# Generated by Django 2.2.10 on 2020-06-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_custom_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='foto',
            field=models.ImageField(blank=True, default='default.png', upload_to='users', verbose_name='Foto'),
        ),
    ]
