# Generated by Django 2.2.10 on 2020-04-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_agenda_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='pedido',
        ),
    ]
