# Generated by Django 2.2 on 2020-03-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20200311_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/profiles'),
        ),
    ]
