# Generated by Django 2.2.10 on 2020-04-27 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_agenda_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='cliente',
        ),
        migrations.AddField(
            model_name='agenda',
            name='pedido',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_agenda', to='web.Pedido', verbose_name='pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
