# Generated by Django 2.2.10 on 2020-04-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20200427_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='servico',
            field=models.CharField(max_length=50, verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='pedidodetail',
            name='servico',
            field=models.CharField(max_length=50, verbose_name='Serviço'),
        ),
    ]
