# Generated by Django 2.2.10 on 2020-04-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20200427_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='nome',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Nome'),
        ),
    ]
