# Generated by Django 2.2 on 2020-03-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_clientemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='images',
            field=models.FileField(blank=True, upload_to='', verbose_name='Imagens'),
        ),
    ]
