# Generated by Django 2.2.10 on 2020-06-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20200616_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='despesas',
            options={'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AlterModelOptions(
            name='fichaanamnese',
            options={'verbose_name': 'Ficha Anamnese', 'verbose_name_plural': 'Fichas Anamnese'},
        ),
        migrations.AlterModelOptions(
            name='pedidodetail',
            options={'verbose_name': 'Pedido Details', 'verbose_name_plural': 'Pedidos Details'},
        ),
        migrations.AlterModelOptions(
            name='registrosessao',
            options={'verbose_name': 'Registro de atendimento', 'verbose_name_plural': 'Registros de atendimentos'},
        ),
    ]
