# Generated by Django 2.2.10 on 2020-06-16 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20200616_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosessao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do Registro'),
            preserve_default=False,
        ),
    ]
