# Generated by Django 2.2 on 2020-03-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_servicos_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='images',
            field=models.FileField(blank=True, upload_to='servicos/imagens/', verbose_name='Imagens'),
        ),
    ]
