# Generated by Django 2.2.10 on 2020-04-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20200427_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_agenda', to='web.ClienteModel', verbose_name='cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_agenda', to='web.PedidoDetail', verbose_name='pedido'),
        ),
    ]
