# Generated by Django 2.2 on 2020-03-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20200311_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='profile', verbose_name='Foto de perfil'),
        ),
    ]
