# Generated by Django 2.2.10 on 2020-06-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_registrosessao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosessao',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data do Registro'),
        ),
    ]
