# Generated by Django 2.2.10 on 2020-05-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20200430_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetail',
            name='servico',
            field=models.ForeignKey(on_delete=models.SET(''), to='web.Servicos'),
        ),
    ]
