# Generated by Django 2.2.10 on 2020-06-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20200616_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosessao',
            name='data',
            field=models.DateTimeField(verbose_name='Data do Registro'),
        ),
    ]
