# Generated by Django 2.2.10 on 2020-05-01 06:43

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20200501_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetail',
            name='servico',
            field=models.ForeignKey(on_delete=models.SET(web.models.Servicos.get_nome), to='web.Servicos'),
        ),
    ]
