# Generated by Django 2.2 on 2020-03-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20200325_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile', verbose_name='Foto de perfil'),
        ),
    ]
