# Generated by Django 2.2.10 on 2020-05-01 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20200501_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetail',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Servicos'),
        ),
    ]
