# Generated by Django 2.2.10 on 2020-05-04 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20200501_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Servicos'),
        ),
    ]
